contact_api:
  resource: "@EvrinomaContactBundle/Controller/ContactApiController.php"
  type: annotation

contact_file_api:
  resource: "@EvrinomaContactBundle/Controller/FileApiController.php"
  type: annotation


