contact_api:
  resource: "@EvrinomaContactBundle/Controller/ContactApiController.php"
  type: annotation

contact_group_api:
  resource: "@EvrinomaContactBundle/Controller/GroupApiController.php"
  type: annotation


