services:
  Evrinoma\ContactBundle\Controller\FileApiController:
    alias: evrinoma.contact.file.api.controller
    public: true

  evrinoma.contact.file.api.controller:
    class: Evrinoma\ContactBundle\Controller\FileApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.contact.file.facade'
    autowire: true

  evrinoma.contact.file.facade:
    class: Evrinoma\ContactBundle\Facade\File\Facade
    arguments:
      - '@evrinoma.contact.file.command.manager'
      - '@evrinoma.contact.file.query.manager'
      - '@evrinoma.contact.adaptor'
    autowire: true

  Evrinoma\ContactBundle\Facade\File\FacadeInterface:
    alias: evrinoma.contact.file.facade

  evrinoma.contact.file.factory:
    class: Evrinoma\ContactBundle\Factory\File\Factory
    public: true
    arguments:

  evrinoma.contact.file.orm.repository:
    class: Evrinoma\ContactBundle\Repository\Orm\File\FileRepository
    public: true
    arguments:

  evrinoma.contact.file.command.manager:
    class: Evrinoma\ContactBundle\Manager\File\CommandManager
    arguments:
      - '@evrinoma.contact.file.validator'
      - '@evrinoma.contact.file.repository'
      - '@evrinoma.contact.file.factory'
      - '@evrinoma.contact.file.command.mediator'
      - '@evrinoma.contact.contact.query.manager'

  Evrinoma\ContactBundle\Manager\File\CommandManagerInterface:
    alias: evrinoma.contact.file.command.manager

  evrinoma.contact.file.query.manager:
    class: Evrinoma\ContactBundle\Manager\File\QueryManager
    arguments:
      - '@evrinoma.contact.file.repository'

  Evrinoma\ContactBundle\Manager\File\QueryManagerInterface:
    alias: evrinoma.contact.file.query.manager

  evrinoma.contact.file.validator:
    class: Evrinoma\ContactBundle\Validator\FileValidator
    public: true
    arguments:

  Evrinoma\ContactBundle\Validator\FileValidator:
    alias: evrinoma.contact.file.validator

  evrinoma.contact.file.query.orm.mediator:
    class: Evrinoma\ContactBundle\Mediator\File\Orm\QueryMediator
    public: true
    arguments:

  Evrinoma\ContactBundle\Mediator\File\Orm\QueryMediator:
    alias: evrinoma.contact.file.query.orm.mediator

  evrinoma.contact.file.command.mediator:
    class: Evrinoma\ContactBundle\Mediator\File\CommandMediator
    public: true

  Evrinoma\ContactBundle\Mediator\File\CommandMediator:
    alias: evrinoma.contact.file.command.mediator

  Evrinoma\ContactBundle\Mediator\File\CommandMediatorInterface:
    alias: evrinoma.contact.file.command.mediator

  evrinoma.contact.file.pre.validator:
    class: Evrinoma\ContactBundle\PreValidator\File\DtoPreValidator
    public: true
    arguments:

  Evrinoma\ContactBundle\PreValidator\File\DtoPreValidator:
    alias: evrinoma.contact.file.pre.validator

  Evrinoma\ContactBundle\PreValidator\File\DtoPreValidatorInterface:
    alias: evrinoma.contact.file.pre.validator

  evrinoma.contact.file.form.rest.file:
    class: Evrinoma\ContactBundle\Form\Rest\File\FileChoiceType
    arguments:
      - '@evrinoma.contact.file.query.manager'
    tags: { - name: form.type }
