services:
  evrinoma.contact.fixtures.contact:
    class: Evrinoma\ContactBundle\Fixtures\ContactFixtures
    tags:
      - { name: doctrine.fixture.orm }

  evrinoma.contact.fixtures.group:
    class: Evrinoma\ContactBundle\Fixtures\GroupFixtures
    tags:
      - { name: doctrine.fixture.orm }
